name: Build app

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/app/**"

defaults:
  run:
    working-directory: src/app
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go get .

      - name: Build app
        run: go build -v ./...
